openapi: 3.0.0
info:
  title: HNG Boilerplate API
  description: A comprehensive API for managing various entities.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
