openapi: 3.0.0
info:
  title: HNG Boilerplate API
  description: A comprehensive API for managing various entities.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - name
        - email
        - password

    Organisation:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - name

paths:
  /api/organisations:
    post:
      summary: Create a new organisation
      security:
       - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organisation'
      responses:
        '201':
          description: Organisation successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organisation'
        '400':
          description: Bad request, invalid input
        '401':
          description: Unauthorized, authentication required
        '403':
          description: Forbidden, user does not have permission



/api/organisations:
  get:
    summary: get all organisations
    security:
      - bearerAuth: []
      requestBody:
        required: true
    responses:
        '200':
          description: Organisation successfully fetched
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Organisation'
         '401':
          description: "Unauthorized, authentication required"

/api/organisations/${id}:
  get:
    summary: get all organisations
    security:
      - bearerAuth: []
      requestBody:
        required: true
    responses:
        '200':
          description: Organisation successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organisation'
          '404':
          description: "Organisation does not exist"
          '400':
          description: "Bad request"
          '401':
          description: "Unauthorized, authentication required"
  

api/notifications:
    get:
      summary: Get all notifications
      responses:
        '200':
          description: Notifications list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    message:
                      type: string
                    timestamp:
                      type: string
                      format: date-time
        '401':
          description: Unauthorized, authentication required
      security:
        - bearerAuth: []


api/notifications/${id}:
  get:
    summary: Get one notification
    response:
    '200':
      description: Notification successfully fetched
      content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: string
            message:
              type: string
            timestamp:
              type: string
              format: date-time
     '401':
          description: Unauthorized, authentication required
       '404':
          description: "Notification does not exist"
      security:
        - bearerAuth: []


 api/invite:
    get:
      summary: Generate an invite link
      responses:
        '200':
          description: Invite link generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  inviteLink:
                    type: string
        '401':
          description: Unauthorized, authentication required
      security:
        - bearerAuth: []

api/email:
    post:
      summary: Send an email to users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                subject:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Bad request, invalid input
        '401':
          description: Unauthorized, authentication required
      security:
        - bearerAuth: []
